# Generated by Django 3.1.7 on 2021-04-22 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('cpf', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroTecnico',
            fields=[
                ('cpf', models.OneToOneField(max_length=20, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.engineer')),
                ('occupation', models.CharField(default='Outros...', max_length=30)),
                ('occupation_number', models.IntegerField(default=0)),
                ('jurisdiction', models.CharField(default='CREA-**', max_length=8)),
                ('elaboration_number', models.IntegerField(default=0)),
                ('elaboration_date', models.DateField()),
                ('ral_jurisdiction', models.CharField(default='CREA-**', max_length=8)),
                ('public_authorization', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ANM', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('substance', models.CharField(max_length=20)),
                ('use', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroOperacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_situation', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=50)),
                ('creation_date', models.DateField(auto_now=True)),
                ('ANM', models.ForeignKey(db_column='ANM', on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
    ]
