# Generated by Django 3.1.7 on 2021-04-20 19:44

from django.db import migrations, models
import django.db.models.deletion
import regex_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('cpf', regex_field.fields.RegexField(max_length=11)),
                ('cnpj', regex_field.fields.RegexField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('ANM', regex_field.fields.RegexField(max_length=12)),
                ('substance', models.CharField(max_length=20)),
                ('use', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CadastroOperacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_situation', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=50)),
                ('ANM_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
    ]
