# Generated by Django 3.1.7 on 2021-04-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrooperacional',
            name='ANM_id',
        ),
        migrations.DeleteModel(
            name='CadastroTecnico',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.DeleteModel(
            name='CadastroOperacional',
        ),
        migrations.DeleteModel(
            name='Engineer',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
