# Generated by Django 3.1.7 on 2021-03-31 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import regex_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_auto_20210319_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('ANM', regex_field.fields.RegexField(max_length=12)),
                ('substance', models.CharField(max_length=20)),
                ('use', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Enginner',
            new_name='Engineer',
        ),
        migrations.DeleteModel(
            name='Relator',
        ),
    ]
