# Generated by Django 3.1.7 on 2021-03-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210331_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='substance',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='use',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
