# Generated by Django 3.1.7 on 2021-04-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cadastrooperacional_cadastrotecnico_engineer_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrotecnico',
            name='ral_jurisdiction',
            field=models.CharField(default='CREA-**', max_length=8),
        ),
        migrations.AlterField(
            model_name='cadastrotecnico',
            name='elaboration_date',
            field=models.DateField(),
        ),
    ]
