# Generated by Django 3.1.7 on 2021-03-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210331_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='substance',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='use',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
